import React, { useState } from 'react';
import {
  Download,
  FileText,
  Code2,
  Printer,
  X,
  Check,
  Copy,
  FileCode,
  Award,
  Scroll,
  QrCode,
  Landmark,
} from 'lucide-react';

export default function ExportModal({ isOpen, onClose, pipelineResult, documentTitle }) {
  const [copied, setCopied] = useState(false);
  const [activePreviewFormat, setActivePreviewFormat] = useState('text'); // 'text' | 'tei' | 'md' | 'json'

  if (!isOpen || !pipelineResult) return null;

  const { preprocessing, ocr, transliteration, translation } = pipelineResult;
  const docTitle = documentTitle || 'KaithiLens_Transcription_Record';

  const generatePlainText = () => {
    return `===============================================================
KAITHILENS HISTORICAL MANUSCRIPT ARCHIVAL REPORT
===============================================================
Document Title: ${docTitle}
OCR Confidence: ${Math.round((ocr?.confidence || 0.95) * 100)}%
Vision Model Engine: ${ocr?.engine || 'KaithiLens Neural Vision Model'}
Timestamp: ${new Date().toUTCString()}

---------------------------------------------------------------
1. ORIGINAL KAITHI TRANSCRIPTION (𑂍𑂶𑂟𑂲)
---------------------------------------------------------------
${ocr?.raw_kaithi || ''}

---------------------------------------------------------------
2. DEVANAGARI TRANSLITERATION (देवनागरी)
---------------------------------------------------------------
${transliteration?.devanagari || ''}

---------------------------------------------------------------
3. ENGLISH SEMANTIC TRANSLATION
---------------------------------------------------------------
${translation?.english || ''}

---------------------------------------------------------------
4. DETECTED HISTORICAL & LEGAL GLOSSARY TERMS
---------------------------------------------------------------
${(translation?.glossary_terms || [])
  .map((t) => `• ${t.term_en} (${t.devanagari}) [${t.category}]: ${t.definition}`)
  .join('\n')}

===============================================================
Preserved with KaithiLens — Restoring South Asian Heritage Archives
===============================================================
`;
  };

  const generateMarkdown = () => {
    return `# Archival Record: ${docTitle}

> **Generated by KaithiLens AI Pipeline**  
> *Date:* ${new Date().toISOString()} • *Confidence:* ${Math.round((ocr?.confidence || 0.95) * 100)}%

---

## 1. Kaithi Script Transcription (𑂍𑂶𑂟𑂲)
\`\`\`kaithi
${ocr?.raw_kaithi || ''}
\`\`\`

## 2. Devanagari Transliteration (देवनागरी)
\`\`\`devanagari
${transliteration?.devanagari || ''}
\`\`\`

## 3. English Semantic Translation
${translation?.english || ''}

## 4. Archival Lexicon & Land Revenue Annotations
| Term (Devanagari) | English | Category | Definition |
| :--- | :--- | :--- | :--- |
${(translation?.glossary_terms || [])
  .map((t) => `| **${t.devanagari}** | ${t.term_en} | \`${t.category}\` | ${t.definition} |`)
  .join('\n')}

---
*Preserved for Digital Humanities & Archival Research.*
`;
  };

  const generateTEIXML = () => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>${docTitle}</title>
        <respStmt>
          <resp>Digitized and Transliterated by</resp>
          <name>KaithiLens Digital Humanities Pipeline</name>
        </respStmt>
      </titleStmt>
      <publicationStmt>
        <p>Digitized Archive Record (${new Date().getFullYear()})</p>
      </publicationStmt>
      <sourceDesc>
        <p>Historical Manuscript from Bihar/UP Land Records</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <div type="transcription" xml:lang="bho-Kthi">
        <p>${(ocr?.raw_kaithi || '').replace(/\n/g, '<lb/>\n        ')}</p>
      </div>
      <div type="transliteration" xml:lang="hi-Deva">
        <p>${(transliteration?.devanagari || '').replace(/\n/g, '<lb/>\n        ')}</p>
      </div>
      <div type="translation" xml:lang="en">
        <p>${(translation?.english || '').replace(/\n/g, '<lb/>\n        ')}</p>
      </div>
    </body>
  </text>
</TEI>`;
  };

  const downloadFile = (content, filename, type) => {
    const element = document.createElement('a');
    const file = new Blob([content], { type });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadTxt = () => {
    downloadFile(generatePlainText(), `${docTitle.replace(/\s+/g, '_')}_KaithiLens.txt`, 'text/plain;charset=utf-8');
  };

  const handleDownloadMd = () => {
    downloadFile(generateMarkdown(), `${docTitle.replace(/\s+/g, '_')}_KaithiLens.md`, 'text/markdown;charset=utf-8');
  };

  const handleDownloadTEI = () => {
    downloadFile(generateTEIXML(), `${docTitle.replace(/\s+/g, '_')}_TEI.xml`, 'application/xml;charset=utf-8');
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(
      {
        metadata: {
          title: docTitle,
          export_date: new Date().toISOString(),
          app: 'KaithiLens v1.0',
        },
        pipeline_data: pipelineResult,
      },
      null,
      2
    );
    downloadFile(jsonStr, `${docTitle.replace(/\s+/g, '_')}_KaithiLens.json`, 'application/json;charset=utf-8');
  };

  const handlePrint = () => {
    window.print();
  };

  const getActiveContent = () => {
    switch (activePreviewFormat) {
      case 'tei':
        return generateTEIXML();
      case 'md':
        return generateMarkdown();
      case 'json':
        return JSON.stringify(pipelineResult, null, 2);
      default:
        return generatePlainText();
    }
  };

  const handleCopyActive = () => {
    navigator.clipboard.writeText(getActiveContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl max-h-[90vh] glass-panel-gold rounded-2xl overflow-hidden flex flex-col shadow-2xl border border-amber-500/30">
        {/* Header */}
        <div className="p-5 border-b border-amber-500/20 flex items-center justify-between bg-slate-100/90 dark:bg-slate-900/60">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-amber-500/20 text-amber-600 dark:text-amber-300 border border-amber-500/30">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-cinzel text-lg font-bold text-slate-900 dark:text-amber-200 tracking-wide">
                Export Archival Dossier
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Download verified transcriptions, digital humanities XML, or print archival certification
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Export Buttons Grid */}
        <div className="p-6 space-y-5 overflow-y-auto">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {/* Plain text */}
            <button
              onClick={handleDownloadTxt}
              className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-900/90 hover:bg-amber-500/20 border border-slate-300 dark:border-slate-700 hover:border-amber-500/50 flex flex-col items-center justify-center text-center space-y-1.5 transition-all group shadow-sm"
            >
              <FileText className="w-6 h-6 text-amber-500 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200 group-hover:text-amber-600 dark:group-hover:text-amber-200">
                Plain Text
              </span>
              <span className="text-[10px] text-slate-500 dark:text-slate-400">.txt report</span>
            </button>

            {/* Markdown */}
            <button
              onClick={handleDownloadMd}
              className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-900/90 hover:bg-amber-500/20 border border-slate-300 dark:border-slate-700 hover:border-amber-500/50 flex flex-col items-center justify-center text-center space-y-1.5 transition-all group shadow-sm"
            >
              <Scroll className="w-6 h-6 text-amber-500 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200 group-hover:text-amber-600 dark:group-hover:text-amber-200">
                Markdown
              </span>
              <span className="text-[10px] text-slate-500 dark:text-slate-400">.md with tables</span>
            </button>

            {/* TEI-XML */}
            <button
              onClick={handleDownloadTEI}
              className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-900/90 hover:bg-amber-500/20 border border-slate-300 dark:border-slate-700 hover:border-amber-500/50 flex flex-col items-center justify-center text-center space-y-1.5 transition-all group shadow-sm"
            >
              <FileCode className="w-6 h-6 text-amber-500 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200 group-hover:text-amber-600 dark:group-hover:text-amber-200">
                TEI-XML
              </span>
              <span className="text-[10px] text-slate-500 dark:text-slate-400">Digital Humanities</span>
            </button>

            {/* JSON Data */}
            <button
              onClick={handleDownloadJson}
              className="p-3.5 rounded-xl bg-slate-100 dark:bg-slate-900/90 hover:bg-amber-500/20 border border-slate-300 dark:border-slate-700 hover:border-amber-500/50 flex flex-col items-center justify-center text-center space-y-1.5 transition-all group shadow-sm"
            >
              <Code2 className="w-6 h-6 text-amber-500 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200 group-hover:text-amber-600 dark:group-hover:text-amber-200">
                JSON Data
              </span>
              <span className="text-[10px] text-slate-500 dark:text-slate-400">Raw coordinates</span>
            </button>
          </div>

          {/* Archival Print Certificate Action */}
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded-lg bg-amber-500/20 text-amber-600 dark:text-amber-300">
                <Printer className="w-5 h-5" />
              </div>
              <div>
                <h4 className="font-cinzel text-xs font-bold text-slate-900 dark:text-amber-200">
                  Print Official Archival Dossier / Save as PDF
                </h4>
                <p className="text-[11px] text-slate-600 dark:text-slate-400">
                  Formatted certificate with institutional header, dual script columns, and seal
                </p>
              </div>
            </div>
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs shadow-md transition-all active:scale-95"
            >
              Print / PDF
            </button>
          </div>

          {/* Live Preview Tabs */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-1.5 text-xs">
                <button
                  onClick={() => setActivePreviewFormat('text')}
                  className={`px-2.5 py-1 rounded-lg transition-colors ${
                    activePreviewFormat === 'text'
                      ? 'bg-amber-500 text-slate-950 font-bold'
                      : 'bg-slate-200 dark:bg-slate-900 text-slate-600 dark:text-slate-400'
                  }`}
                >
                  Plain Text
                </button>
                <button
                  onClick={() => setActivePreviewFormat('md')}
                  className={`px-2.5 py-1 rounded-lg transition-colors ${
                    activePreviewFormat === 'md'
                      ? 'bg-amber-500 text-slate-950 font-bold'
                      : 'bg-slate-200 dark:bg-slate-900 text-slate-600 dark:text-slate-400'
                  }`}
                >
                  Markdown
                </button>
                <button
                  onClick={() => setActivePreviewFormat('tei')}
                  className={`px-2.5 py-1 rounded-lg transition-colors ${
                    activePreviewFormat === 'tei'
                      ? 'bg-amber-500 text-slate-950 font-bold'
                      : 'bg-slate-200 dark:bg-slate-900 text-slate-600 dark:text-slate-400'
                  }`}
                >
                  TEI-XML
                </button>
                <button
                  onClick={() => setActivePreviewFormat('json')}
                  className={`px-2.5 py-1 rounded-lg transition-colors ${
                    activePreviewFormat === 'json'
                      ? 'bg-amber-500 text-slate-950 font-bold'
                      : 'bg-slate-200 dark:bg-slate-900 text-slate-600 dark:text-slate-400'
                  }`}
                >
                  JSON
                </button>
              </div>

              <button
                onClick={handleCopyActive}
                className="flex items-center space-x-1 text-xs text-amber-600 dark:text-amber-400 hover:underline transition-colors"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-500" />
                    <span className="text-emerald-500 font-semibold">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Preview</span>
                  </>
                )}
              </button>
            </div>

            <pre className="p-4 rounded-xl bg-slate-900 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 text-[11px] font-mono text-slate-200 max-h-48 overflow-y-auto whitespace-pre-wrap leading-relaxed">
              {getActiveContent()}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-300 dark:border-slate-800 bg-slate-100/90 dark:bg-slate-950/80 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
